/**
 * Utility functions for exporting voice memo tasks in various formats.
 */

interface Task {
  description: string;
  priority: 'High' | 'Medium' | 'Low';
  category?: string;
  time_estimate?: string;
  notes?: string;
  depends_on?: string;
}

interface ExportMetadata {
  transcript: string;
  summary: string;
  language: string;
  duration: number;
  confidence: number;
  timestamp: string;
}

/**
 * Export tasks as Markdown format
 */
export function exportTasksAsMarkdown(
  tasks: Task[],
  metadata: ExportMetadata
): string {
  const lines: string[] = [];

  // Header
  lines.push('# Voice Memo Tasks');
  lines.push('');

  // Metadata
  lines.push('## Details');
  lines.push(`- **Date:** ${metadata.timestamp}`);
  lines.push(`- **Duration:** ${metadata.duration.toFixed(1)}s`);
  lines.push(`- **Language:** ${metadata.language.toUpperCase()}`);
  lines.push(`- **Confidence:** ${(metadata.confidence * 100).toFixed(1)}%`);
  lines.push('');

  // Summary
  lines.push('## Summary');
  lines.push(metadata.summary);
  lines.push('');

  // Tasks
  lines.push('## Tasks');
  lines.push('');

  // Count by priority
  const highPriority = tasks.filter((t) => t.priority === 'High');
  const mediumPriority = tasks.filter((t) => t.priority === 'Medium');
  const lowPriority = tasks.filter((t) => t.priority === 'Low');

  if (highPriority.length > 0) {
    lines.push('### 🔴 High Priority');
    highPriority.forEach((task) => {
      lines.push(`- [ ] ${task.description}`);
      if (task.time_estimate) {
        lines.push(`  - ⏱️ ${task.time_estimate}`);
      }
      if (task.category) {
        lines.push(`  - 📁 ${task.category}`);
      }
      if (task.notes) {
        lines.push(`  - 📝 ${task.notes}`);
      }
    });
    lines.push('');
  }

  if (mediumPriority.length > 0) {
    lines.push('### 🟡 Medium Priority');
    mediumPriority.forEach((task) => {
      lines.push(`- [ ] ${task.description}`);
      if (task.time_estimate) {
        lines.push(`  - ⏱️ ${task.time_estimate}`);
      }
      if (task.category) {
        lines.push(`  - 📁 ${task.category}`);
      }
      if (task.notes) {
        lines.push(`  - 📝 ${task.notes}`);
      }
    });
    lines.push('');
  }

  if (lowPriority.length > 0) {
    lines.push('### 🟢 Low Priority');
    lowPriority.forEach((task) => {
      lines.push(`- [ ] ${task.description}`);
      if (task.time_estimate) {
        lines.push(`  - ⏱️ ${task.time_estimate}`);
      }
      if (task.category) {
        lines.push(`  - 📁 ${task.category}`);
      }
      if (task.notes) {
        lines.push(`  - 📝 ${task.notes}`);
      }
    });
    lines.push('');
  }

  // Transcript
  lines.push('## Transcript');
  lines.push('');
  lines.push('```');
  lines.push(metadata.transcript);
  lines.push('```');
  lines.push('');

  // Footer
  lines.push('---');
  lines.push('*Generated by NexusAI Voice Memos to Tasks*');

  return lines.join('\n');
}

/**
 * Export tasks as JSON format
 */
export function exportTasksAsJSON(tasks: Task[], metadata: ExportMetadata): string {
  const data = {
    metadata: {
      timestamp: metadata.timestamp,
      duration: metadata.duration,
      language: metadata.language,
      confidence: metadata.confidence,
      task_count: tasks.length,
    },
    summary: metadata.summary,
    transcript: metadata.transcript,
    tasks: tasks.map((task, index) => ({
      id: index + 1,
      ...task,
    })),
    statistics: {
      total: tasks.length,
      high_priority: tasks.filter((t) => t.priority === 'High').length,
      medium_priority: tasks.filter((t) => t.priority === 'Medium').length,
      low_priority: tasks.filter((t) => t.priority === 'Low').length,
      total_time_minutes: calculateTotalTime(tasks),
    },
  };

  return JSON.stringify(data, null, 2);
}

/**
 * Calculate total time estimate from tasks
 */
function calculateTotalTime(tasks: Task[]): number {
  let totalMinutes = 0;

  tasks.forEach((task) => {
    if (task.time_estimate) {
      const match = task.time_estimate.match(/(\d+)\s*(min|hour|h)/i);
      if (match) {
        const value = parseInt(match[1], 10);
        const unit = match[2].toLowerCase();

        if (unit === 'hour' || unit === 'h') {
          totalMinutes += value * 60;
        } else if (unit === 'min') {
          totalMinutes += value;
        }
      }
    }
  });

  return Math.round((totalMinutes / 60) * 10) / 10; // Round to 1 decimal place
}

/**
 * Download text as file
 */
export function downloadAsFile(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Generate filename with timestamp
 */
export function generateFilename(format: 'md' | 'json'): string {
  const now = new Date();
  const dateStr = now.toISOString().split('T')[0]; // YYYY-MM-DD
  const timeStr = now.toTimeString().split(' ')[0].replace(/:/g, '-'); // HH-MM-SS
  const ext = format === 'md' ? 'md' : 'json';
  return `voice-memo-${dateStr}_${timeStr}.${ext}`;
}
